name: simplesonic
dependencies:
    - python==3.6
    - scikit-learn
    - cython
    - openblas
    - numpy
    - matplotlib
    - bokeh
    - pillow
    - scikit-image
    - scipy
    - h5py
    - pandas
    - pip:
        - jupyter
        - moviepy
        - tensorflow-gpu==1.8.0
        - keras
        - pydot
        - nltk
        - pandas-gbq
        - awscli
        - google-cloud
        - pyvirtualdisplay
        - gym
        - gym-retro
        - opencv-python
